//! MFA (Multi-Factor Authentication) Demo
//!
//! Demonstrates TOTP functionality including:
//! - Secret generation
//! - QR code creation
//! - Code verification

#[cfg(feature = "mfa")]
use mcp_rs::security::mfa::*;

#[cfg(feature = "mfa")]
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("=== MFA (Multi-Factor Authentication) Demo ===\n");

    // Create MFA configuration
    let config = TotpConfig::default();
    println!("✓ TOTP Configuration:");
    println!("  - Algorithm: {:?}", config.algorithm);
    println!("  - Digits: {}", config.digits);
    println!("  - Period: {} seconds", config.period);
    println!("  - Time Window: ±{} steps\n", config.time_window);

    // Generate TOTP secret
    println!("--- Step 1: Generate TOTP Secret ---");
    let secret = TotpSecret::generate(&config)?;
    println!("✓ Secret generated: {}", secret.encoded());
    println!();

    // Generate QR code
    println!("--- Step 2: Generate QR Code ---");
    let qr_code = secret.to_qr_code("MCP-RS Demo", "user@example.com")?;
    println!("✓ QR code generated ({} bytes)", qr_code.len());

    // Save QR code to file (optional)
    std::fs::write("totp_qr_code.png", &qr_code)?;
    println!("✓ QR code saved to: totp_qr_code.png");
    println!("  Scan this with your authenticator app (Google Authenticator, Authy, etc.)\n");

    // Generate otpauth URI
    let uri = secret.to_uri("MCP-RS Demo", "user@example.com");
    println!("--- Step 3: OTP Auth URI ---");
    println!("{}\n", uri);

    // Create verifier
    let verifier = TotpVerifier::new(config);

    // Generate current code
    println!("--- Step 4: Generate Current Code ---");
    let current_code = verifier.generate_code(&secret)?;
    println!("✓ Current TOTP code: {}", current_code);
    println!();

    // Verify the code
    println!("--- Step 5: Verify Code ---");
    match verifier.verify(&secret, &current_code) {
        Ok(true) => println!("✓ Code verified successfully!"),
        Ok(false) => println!("✗ Code verification failed"),
        Err(e) => println!("✗ Verification error: {}", e),
    }
    println!();

    // Test invalid code
    println!("--- Step 6: Test Invalid Code ---");
    match verifier.verify(&secret, "000000") {
        Ok(true) => println!("✗ Invalid code accepted (should not happen!)"),
        Ok(false) => println!("✓ Invalid code correctly rejected"),
        Err(e) => println!("✗ Verification error: {}", e),
    }
    println!();

    // Test different algorithms
    println!("--- Step 7: Test Different Algorithms ---");
    for algorithm in [
        TotpAlgorithm::Sha1,
        TotpAlgorithm::Sha256,
        TotpAlgorithm::Sha512,
    ] {
        let algo_config = TotpConfig {
            algorithm,
            ..Default::default()
        };
        let algo_secret = TotpSecret::generate(&algo_config)?;
        let algo_verifier = TotpVerifier::new(algo_config);
        let algo_code = algo_verifier.generate_code(&algo_secret)?;

        println!("  {:?}: code={}", algorithm, algo_code);
    }
    println!();

    // Test 8-digit codes
    println!("--- Step 8: Test 8-Digit Codes ---");
    let eight_digit_config = TotpConfig {
        digits: 8,
        ..Default::default()
    };
    let eight_digit_secret = TotpSecret::generate(&eight_digit_config)?;
    let eight_digit_verifier = TotpVerifier::new(eight_digit_config);
    let eight_digit_code = eight_digit_verifier.generate_code(&eight_digit_secret)?;

    println!("✓ 8-digit code: {}", eight_digit_code);
    assert_eq!(eight_digit_code.len(), 8);
    println!();

    // Demonstration of time window
    println!("--- Step 9: Time Window Demonstration ---");
    println!(
        "The time window allows codes from ±{} time steps",
        verifier.config().time_window
    );
    println!(
        "This means codes from {} seconds before/after are valid",
        verifier.config().time_window as u64 * verifier.config().period
    );
    println!();

    println!("=== Demo Complete ===");
    println!("\n💡 Next Steps:");
    println!("  1. Scan totp_qr_code.png with your authenticator app");
    println!("  2. Compare the codes generated by the app with this demo");
    println!("  3. Use the TOTP functionality in your application");

    Ok(())
}

#[cfg(not(feature = "mfa"))]
fn main() {
    println!("このデモを実行するには、mfaフィーチャーを有効にしてください。");
    println!("cargo run --example mfa_totp_demo --features mfa");
}
